CREATE TABLE AD(
                 ID_AD NUMBER NOT NULL PRIMARY KEY,
                 ID_USER NUMBER,
                 CONSTRAINT AD_USER_FK FOREIGN KEY(ID_USER)REFERENCES USER_DZ7(ID),
                 AD_NAME NVARCHAR2(50) NOT NULL,
                 AD_DESCRIPTION NVARCHAR2(200) NOT NULL,
                 PRICE NUMBER NOT NULL,
                 CITY NVARCHAR2(20) NOT NULL,
                 NUMBER_PHONE NVARCHAR2(15) NOT NULL,
                 DATE_FROM TIMESTAMP,
                 DATE_TO TIMESTAMP,
                 CURRENCY_TYPE NVARCHAR2(5) NOT NULL CHECK(CURRENCY_TYPE = 'USD' OR CURRENCY_TYPE = 'EUR' OR CURRENCY_TYPE = 'UAH'),
                 CATEGORY_TYPE NVARCHAR2(50) NOT NULL CHECK(CATEGORY_TYPE = 'SALE' OR CATEGORY_TYPE = 'BUY'),
                 SUBCATEGORY_TYPE NVARCHAR2(20) NOT NULL CHECK(SUBCATEGORY_TYPE = 'AUTO' OR SUBCATEGORY_TYPE = 'APARTMENTS' OR
                                                               SUBCATEGORY_TYPE = 'HOUSES')
);

CREATE SEQUENCE AD_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;