CREATE TABLE SUBCATEGORY(
ID_SUBCATEGORY NUMBER NOT NULL PRIMARY KEY,
ID_CATEGORY_SUBCATEGORY NUMBER,
CONSTRAINT CATEGORY_SUBCATEGORY_FK FOREIGN KEY(ID_CATEGORY_SUBCATEGORY)REFERENCES CATEGORY_MESSAGE(ID_CATEGORY),
SUBCATEGORY_NAME NVARCHAR2(20) NOT NULL,
SUBCATEGORY_CITY NVARCHAR2(20) NOT NULL,
NUMBER_PHONE NVARCHAR2(20) NOT NULL,
DATE_FROM TIMESTAMP NOT NULL,
DATE_TO TIMESTAMP NOT NULL
);

CREATE SEQUENCE SUBCATEGORY_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;