CREATE TABLE MESSAGE(
ID_MESSAGE NUMBER NOT NULL PRIMARY KEY,
ID_USER NUMBER,
CONSTRAINT MESSAGE_USER_FK FOREIGN KEY(ID_USER)REFERENCES USER_DZ7(ID),
MESSAGE_NAME NVARCHAR2(50) NOT NULL,
MESSAGE_DESCRIPTION NVARCHAR2(200) NOT NULL,
PRICE NUMBER NOT NULL,
CURRENCY_TYPE NVARCHAR2(5) NOT NULL CHECK(CURRENCY_TYPE = 'USD' OR CURRENCY_TYPE = 'EUR' OR CURRENCY_TYPE = 'UAH')
);

CREATE SEQUENCE MESSAGE_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;