CREATE TABLE USER_DZ7(
ID NUMBER NOT NULL PRIMARY KEY,
USER_NAME NVARCHAR2(50) NOT NULL,
USER_PASSWORD NVARCHAR2(20) NOT NULL,
LOGIN_TYPE NVARCHAR2(20) NOT NULL CHECK(LOGIN_TYPE = 'INSYSTEM' OR LOGIN_TYPE = 'OUTSYSTEM'),
USER_TYPE NVARCHAR2(20) NOT NULL CHECK(USER_TYPE = 'REGISTER' OR USER_TYPE = 'UNREGISTER')
);

CREATE SEQUENCE USER7_SEQ MINVALUE 1 MAXVALUE 10000 START WITH 1 INCREMENT BY 1;